#pragma once

//From glfw3.h
#define IMPCT_MOUSE_BUTTON_1         0
#define IMPCT_MOUSE_BUTTON_2         1
#define IMPCT_MOUSE_BUTTON_3         2
#define IMPCT_MOUSE_BUTTON_4         3
#define IMPCT_MOUSE_BUTTON_5         4
#define IMPCT_MOUSE_BUTTON_6         5
#define IMPCT_MOUSE_BUTTON_7         6
#define IMPCT_MOUSE_BUTTON_8         7
#define IMPCT_MOUSE_BUTTON_LAST      IMPCT_MOUSE_BUTTON_8
#define IMPCT_MOUSE_BUTTON_LEFT      IMPCT_MOUSE_BUTTON_1
#define IMPCT_MOUSE_BUTTON_RIGHT     IMPCT_MOUSE_BUTTON_2
#define IMPCT_MOUSE_BUTTON_MIDDLE    IMPCT_MOUSE_BUTTON_3